app_blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'app_blog'

urlpatterns = [

    # url for CRUD Post
    path('post/create', views.PostCreateView.as_view(), name="post-create",),
    path('post/list/', views.PostListView.as_view(), name="post-list"),
    path('post/<int:pk>/detail/', views.PostDetailView.as_view(), name="post-detail"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name="post-delete"),

    # url for CRUD Comment
    # retrieve comment is done at home (project/urls.py)
    path('comment/<int:pk>/create/', views.CommmentAddView.as_view(), name="comment-create"),
    path('comment/<int:pk>/reply/', views.replyComment, name="comment-reply"),
    path('comment/list/', views.CommentListView.as_view(), name="comment-list"),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name="comment-update"),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name="comment-delete"),
    path('comment/<int:pk>/detail/', views.CommentDetailView.as_view(), name="comment-detail"),

    path('comment/<int:pk>/reply/create/', views.ReplyCommentCreateView.as_view(), name="reply-comment-create"),
   

    # url for CRUD Series
    path('series/create/', views.SeriesCreateView.as_view(), name="series-create",),
     path('series/list/', views.SeriesListView.as_view(), name="series-list"),
    path('series/<int:pk>/detail/', views.SeriesDetailView.as_view(), name="series-detail"),
    path('series/<int:pk>/update/', views.SeriesUpdateView.as_view(), name="series-update"),
    path('series/<int:pk>/delete/', views.SeriesDeleteView.as_view(), name="series-delete"),

    # url for CRUD Tag
    path('tag/create/', views.TagCreateView.as_view(), name="tag-create",),
    path('tag/list/', views.TagListView.as_view(), name="tag-list"),
    path('tag/<int:pk>/detail/', views.TagDetailView.as_view(), name="tag-detail"),
    path('tag/<int:pk>/update/', views.TagUpdateView.as_view(), name="tag-update"),
    path('tag/<int:pk>/delete/', views.TagDeleteView.as_view(), name="tag-delete"),


    # API
    path('api/api_one', views.api_one, name="api_one"),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="blog-home"), # project home
    path('blog/', include('app_blog.urls', namespace='app_blog')), # extends into app_blog urls
    path('accounts/', include("django.contrib.auth.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/models.py
from django.db import models
from django.conf import settings

class Tag(models.Model):
    name = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='contributed_posts', blank=True)
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
    series = models.ForeignKey(Series, on_delete=models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now= True)
    sequence = models.IntegerField(default=1)

    class Meta:
        ordering = ['sequence', '-created_on'] 

    def __str__(self):
        if self.author:
            return f'{self.title} ({self.author})'
        else:
            return f'{self.title}'

    def save(self, *args, **kwargs):
        # Check if there is any existing post with the same sequence
        same_sequence_posts = Post.objects.filter(sequence=self.sequence).exclude(pk=self.pk)
        
        # If there are any posts with the same sequence, increment their sequence by 1
        if same_sequence_posts.exists():
            for post in same_sequence_posts:
                post.sequence += 1
                post.save()

        # Call the original save() method to save the post
        super(Post, self).save(*args, **kwargs)

class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.FileField(null= True, blank=True, upload_to='uploads/%Y/%m/%d/')

class Comment(models.Model):
    commenter = models.CharField(max_length=100, default="")
    comment_detail = models.TextField(default="")
    comment_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent=models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.commenter

app_blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm, ClearableFileInput
from .models import Post, Comment, Tag
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError

    
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "tags", "series", "contributors"]

    files = forms.FileField(
        widget=ClearableFileInput(attrs={"multiple": True}), required=False
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super(PostForm, self).__init__(*args, **kwargs)
        if self.user:
            # Exclude the current user from the list of contributors
            self.fields["contributors"].queryset = get_user_model().objects.exclude(
                id=self.user.id
            )

        super(PostForm, self).__init__(*args, **kwargs)
        self.fields["tags"].widget.attrs.update({"class": "form-control"})
        self.fields["series"].widget.attrs.update({"class": "form-control"})
        self.fields["contributors"].widget.attrs.update({"class": "form-control"})

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div

# Define a form class to be used for ReplyCommentCreateView
class ReplyCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            "comment_detail",
            "commenter",
        )

    def __init__(self, *args, pk=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.pk = pk

        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2'
        self.helper.field_class = 'col-sm-8'
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn btn-primary'))



    # Clean the form to assign the parent comment and post to the reply comment
    def clean(self):
        
        # Get the comment to be created
        cleaned_data = super().clean()
        instance = self.instance

        # Get the pk kwargs from the url
        pk = self.pk

        # Assign the parent comment to the instance
        instance.parent = get_object_or_404(Comment, pk=pk)

        # Assign the post to the instance
        instance.post = instance.parent.post

        # Done
        return cleaned_data



class generalErrorMixin:
    def clean(self):
        # Check if any field has an error
        if self.errors:
            raise forms.ValidationError("Please fix the errors below and try again")
        
class TagCreateForm(generalErrorMixin, forms.ModelForm):

    class Meta:
        model = Tag
        fields = (
            "name",
        )

    def clean_name(self):
        super().clean()
        name = self.cleaned_data['name']
        matching_tags = Tag.objects.filter(name__iexact=name)

        error_collection = []

        if matching_tags.exists():
            # The name matches a record in the database
            # You can raise a validation error or perform further actions as needed
            error_collection.append("Tag name already exists.")

        if error_collection:
            raise forms.ValidationError(error_collection)
        
        return name

app_blog/views.py
from typing import Any
from django.shortcuts import render, redirect
from .models import Post, Comment, Series, Tag, PostFile
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .forms import PostForm, TagCreateForm


# API endpoint for api_one
def api_one(request):
    return JsonResponse({"message": "Hello, World!"})


# Create your views here.
def blog_home(request):
    context = {}
    context["visitor_name"] = request.user
    return render(request, "app_blog/home.html", context=context)


# Class Based View Model
# Model Series CRUD
class SeriesListView(ListView):
    model = Series
    template_name = "app_blog/series/series_list.html"


class SeriesDetailView(DetailView):
    model = Series
    template_name = "app_blog/series/series_detail.html"
    context_object_name = "series"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = Post.objects.filter(series=self.object)
        context["x"] = 1
        return context


class SeriesCreateView(CreateView):
    model = Series
    template_name = "app_blog/series/series_form.html"
    fields = "__all__"
    success_url = reverse_lazy("app_blog:series-list")


class SeriesUpdateView(UpdateView):
    model = Series
    template_name = "app_blog/series/series_update.html"
    fields = "__all__"
    success_url = reverse_lazy(
        "app_blog:series-list"
    )  # when a Post is successfully updated, redirect to this url


class SeriesDeleteView(DeleteView):
    model = Series
    template_name = "app_blog/series/series_confirm_delete.html"
    success_url = reverse_lazy("app_blog:series-list")


# Model Post CRUD
class PostListView(ListView):
    model = Post
    template_name = "app_blog/post/post_list.html"


class PostDetailView(DetailView):
    model = Post
    template_name = "app_blog/post/post_detail.html"


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "app_blog/post/post_form.html"
    success_url = reverse_lazy("app_blog:post-list")

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        for f in self.request.FILES.getlist("files"):
            PostFile.objects.create(post=post, file=f)
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    # Behind the scenes,
    # 1) form is automatically generated and accessible via {{ form }} in template
    # Error message included, previously submitted values in tact
    # Default server-side validation
    # Default client-side validation


class PostUpdateView(UpdateView):
    model = Post
    fields = "__all__"
    template_name = "app_blog/post/post_update.html"
    success_url = reverse_lazy(
        "app_blog:post-list"
    )  # when a Post is successfully updated, redirect to this url


class PostDeleteView(DeleteView):
    model = Post
    template_name = "app_blog/post/post_confirm_delete.html"
    success_url = reverse_lazy("app_blog:post-list")


# Model Comment CRUD
class CommmentAddView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ["comment_detail"]
    template_name = "app_blog/comment/comment_form.html"
    success_url = reverse_lazy("app_blog:comment-list")

    def form_valid(self, form):
        post_id = get_object_or_404(Post, pk=self.kwargs["pk"])
        form.instance.post = post_id
        form.instance.commenter = self.request.user

        return super().form_valid(form)


def replyComment(request, pk):
    parent_comment = Comment.objects.get(id=pk)

    if request.method == "POST":
        replier_name = request.user
        reply_content = request.POST.get("reply_content")
        postid = request.POST.get("postID")
        post = Post.objects.get(id=postid)
        newReply = Comment(
            commenter=replier_name,
            comment_detail=reply_content,
            post=post,
            parent=parent_comment,
        )
        newReply.save()
        return redirect("app_blog:comment-list")


from .forms import ReplyCommentForm

class GetURLPKMixin:
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["pk"] = self.kwargs.get("pk")
        return kwargs

class ReplyCommentCreateView(LoginRequiredMixin, GetURLPKMixin, CreateView):
    model = Comment
    form_class = ReplyCommentForm
    template_name = "app_blog/comment/reply_comment_form.html"
    success_url = reverse_lazy("app_blog:comment-list")

    # Ensure that a comment with the url pk exists when a user visits the page
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=self.kwargs["pk"])
        return super().get(request, *args, **kwargs)

    # Assign the parent comment and post to the reply comment
    # def form_valid(self, form):

    #     # Get the comment to be created
    #     instance = form.instance

    #     # Assign the parent comment to the instance
    #     instance.parent = get_object_or_404(Comment, pk=self.kwargs['pk'])

    #     # Assign the post to the instance
    #     instance.post = instance.parent.post

    #     # Done
    #     return super().form_valid(form)


class CommentUpdateView(UpdateView):
    model = Comment
    fields = ["comment_detail"]
    template_name = "app_blog/comment/comment_update.html"
    success_url = reverse_lazy(
        "app_blog:comment-list"
    )  # when a Post is successfully updated, redirect to this url


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = "app_blog/comment/comment_confirm_delete.html"
    success_url = reverse_lazy("app_blog:comment-list")


class CommentListView(ListView):
    model = Comment
    template_name = "app_blog/comment/comment_list.html"


class CommentDetailView(DetailView):
    model = Comment
    template_name = "app_blog/comment/comment_detail.html"


# Model Tag CRUD
class TagListView(ListView):
    model = Tag
    template_name = "app_blog/tag/tag_list.html"


class TagDetailView(DetailView):
    model = Tag
    template_name = "app_blog/tag/tag_detail.html"


class TagCreateView(CreateView):
    model = Tag
    form_class = TagCreateForm
    template_name = "app_blog/tag/tag_form.html"
    success_url = reverse_lazy("app_blog:tag-list")


class TagUpdateView(UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "app_blog/tag/tag_update.html"
    success_url = reverse_lazy(
        "app_blog:tag-list"
    )  # when a Post is successfully updated, redirect to this url


class TagDeleteView(DeleteView):
    model = Tag
    template_name = "app_blog/tag/tag_confirm_delete.html"
    success_url = reverse_lazy("app_blog:tag-list")

app_blog/templates/app_blog/series/series_confirm_delete.html
{% extends "app_blog/base.html" %}

{% block title %}
  Delete Series
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
    <li>
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}

<h1>Delete Confirmation</h1>
<p>Are you sure you want to delete Series "{{ object.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-primary" style="background-color:#f48840; border-color: #f48840;" />
    <a href="{% url 'app_blog:series-list' %}">Cancel</a>
</form>
{% endblock %}

app_blog/templates/app_blog/series/series_detail.html
{% extends "app_blog/base.html" %}

{% block title %}
  Series Detail
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
    <li>
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

        <h1 class="display-4" style="text-align: center;">Series <i>{{ series.name }}</i> Detail</h1>
        <br/>
        <div style="text-align: center;">
            <a href="{% url 'app_blog:series-update' series.pk %}" class="btn btn-primary">Edit Series Name -- {{ series.name }}</a>
            &nbsp;
            <a href="{% url 'app_blog:series-delete' series.pk %}" class="btn btn-danger">Delete Series Name -- {{ series.name }}</a>
        </div>
        <br/><br/>
        <table id="blogTable" class="table display" style="text-align: center;">
            <thead>
                <th>No</th>
                <th>Title</th>
                <th>Author</th>
                <th>Sequence (Tetsing Purpose)</th>
            </thead>
            <tbody style="text-align: left;">
                {% for post in post %}
                    {% with forloop.counter as seq %}
                        <tr>
                            <td>
                                {{ forloop.counter }}
                            </td>
                            <td>
                                <a href="{% url 'app_blog:post-detail' post.pk %}">
                                    {{ post.title }}
                                </a>                  
                            </td>
                            <td>{{ post.author }}</td>
                            <td>{{ post.sequence }}</td> // testing purpose
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </body>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <script>

        var table = $('#blogTable').DataTable({
            //serverSide: true,
        });

    </script>

{% endblock %}

app_blog/templates/app_blog/series/series_form.html
{% extends "app_blog/base.html" %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}



{% block title %}
  Series Post
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
    <li>
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
        <h1 class="display-4" style="text-align: center;">New Series</h1>
        <div class="container">
            <div class="row my-5">
                <div class="col-md-12">
                    <form method="post">
                        {% csrf_token %}
                        {{form| crispy}}
                        <input type="submit" class="btn btn-primary" value="Create New Series" />
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

app_blog/templates/app_blog/series/series_list.html
{% extends "app_blog/base.html" %}

{% block title %}
  Series List
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
    <li>
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}

        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

        <h1 class="display-4" style="text-align: center;">Series List</h1>

        <table id="blogTable" class="table display" style="text-align: center;">
            <thead>
                <th>No</th>
                <th>Series Name</th>
                <th>Number of Posts</th>
                <th>Posts</th>
                <th>Action</th>
            </thead>
            <tbody style="text-align: left;">
                {% for s in object_list %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>
                            <a href="{% url 'app_blog:series-detail' s.id %}">
                                {{ s.name }}
                            </a>                  
                        </td>
                        <td>{{ s.post_set.all.count }}</td>
                        <td>
                            <ol>
                                {% for post in s.post_set.all %}
                                    <li>{{ post.title }}</li>
                                {% empty %}
                                    <span class="text-muted">
                                        No posts related
                                    </span>
                                {% endfor %}
                            </ol>
                        </td>
                        <td> 
                            <a href="{% url 'app_blog:series-delete' s.id %}" class="btn btn-danger">Delete</a>
                            <a href="{% url 'app_blog:series-update' s.id %}" class="btn btn-success">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'app_blog:series-create' %}" class="btn btn-primary">Create new series</a>
    </body>

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <script>

        var table = $('#blogTable').DataTable({
            //serverSide: true,
        });

    </script>

{% endblock %}

app_blog/templates/app_blog/series/series_update.html
{% extends "app_blog/base.html" %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}



{% block title %}
  Series Post
{% endblock %}

{% block navbar %}
    {% if user.is_authenticated %}
    <li>
    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
    </li>
    {% endif %}
{% endblock %}

{% block content %}
        <h1 class="display-4" style="text-align: center;">Update Series</h1>
        <div class="container">
            <div class="row my-5">
                <div class="col-md-12">
                    <form method="post">
                        {% csrf_token %}
                        {{form| crispy}}
                        <input type="submit" class="btn btn-primary" value="Update Series" />
                    </form>
                </div>
            </div>
        </div>
{% endblock %}