app_blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'app_blog'

urlpatterns = [

    # url for CRUD Post
    path('post/create', views.PostCreateView.as_view(), name="post-create",),
    path('post/list/', views.PostListView.as_view(), name="post-list"),
    path('post/<int:pk>/detail/', views.PostDetailView.as_view(), name="post-detail"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name="post-delete"),

    # url for CRUD Comment
    # retrieve comment is done at home (project/urls.py)
    path('comment/<int:pk>/create/', views.CommmentAddView.as_view(), name="comment-create"),
    path('comment/<int:pk>/reply/', views.replyComment, name="comment-reply"),
    path('comment/list/', views.CommentListView.as_view(), name="comment-list"),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name="comment-update"),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name="comment-delete"),
    path('comment/<int:pk>/detail/', views.CommentDetailView.as_view(), name="comment-detail"),

    path('comment/<int:pk>/reply/create/', views.ReplyCommentCreateView.as_view(), name="reply-comment-create"),
   

    # url for CRUD Series
    path('series/create/', views.SeriesCreateView.as_view(), name="series-create",),
     path('series/list/', views.SeriesListView.as_view(), name="series-list"),
    path('series/<int:pk>/detail/', views.SeriesDetailView.as_view(), name="series-detail"),
    path('series/<int:pk>/update/', views.SeriesUpdateView.as_view(), name="series-update"),
    path('series/<int:pk>/delete/', views.SeriesDeleteView.as_view(), name="series-delete"),

    # url for CRUD Tag
    path('tag/create/', views.TagCreateView.as_view(), name="tag-create",),
    path('tag/list/', views.TagListView.as_view(), name="tag-list"),
    path('tag/<int:pk>/detail/', views.TagDetailView.as_view(), name="tag-detail"),
    path('tag/<int:pk>/update/', views.TagUpdateView.as_view(), name="tag-update"),
    path('tag/<int:pk>/delete/', views.TagDeleteView.as_view(), name="tag-delete"),


    # API
    path('api/api_one', views.api_one, name="api_one"),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="blog-home"), # project home
    path('blog/', include('app_blog.urls', namespace='app_blog')), # extends into app_blog urls
    path('accounts/', include("django.contrib.auth.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/models.py
from django.db import models
from django.conf import settings

class Tag(models.Model):
    name = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='contributed_posts', blank=True)
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
    series = models.ForeignKey(Series, on_delete=models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now= True)
    sequence = models.IntegerField(default=1)

    class Meta:
        ordering = ['sequence', '-created_on'] 

    def __str__(self):
        if self.author:
            return f'{self.title} ({self.author})'
        else:
            return f'{self.title}'

    def save(self, *args, **kwargs):
        # Check if there is any existing post with the same sequence
        same_sequence_posts = Post.objects.filter(sequence=self.sequence).exclude(pk=self.pk)
        
        # If there are any posts with the same sequence, increment their sequence by 1
        if same_sequence_posts.exists():
            for post in same_sequence_posts:
                post.sequence += 1
                post.save()

        # Call the original save() method to save the post
        super(Post, self).save(*args, **kwargs)

class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.FileField(null= True, blank=True, upload_to='uploads/%Y/%m/%d/')

class Comment(models.Model):
    commenter = models.CharField(max_length=100, default="")
    comment_detail = models.TextField(default="")
    comment_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent=models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.commenter

project/views.py
from django.shortcuts import render
from django.http import HttpResponse
from app_blog.models import Post, Comment, Tag, Series

def home(request):
    context = {}
    context['post'] = Post.objects.all()
    context['tags'] = Tag.objects.all()
    context['comment'] = Comment.objects.all()
    context['series'] = Series.objects.all()
    
    return render(request, 'project/home.html', context=context)

project/templates/project/home.html
{% extends 'project/master.html' %}
{% load static %}

{% block title %} My Blog {% endblock %}

{% block content %}
        {% if user.is_authenticated %}
        <li>
          <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>
<!-- Page Content -->
<!-- Banner Starts Here -->
<div class="main-banner header-text">
  <div class="container-fluid">
    <div class="owl-banner owl-carousel"></div>
  </div>
</div>

<!-- Banner Ends Here -->
<section class="call-to-action">
  {% if user.is_authenticated %}
    <div class="alert alert-success alert-dismissible fade show" role="alert" style="width:80%; margin-left: auto; margin-right: auto;">
      <h4 style="text-align: center;">Welcome Back, {{ user.username }}.</h4> 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% else %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert" style="width:80%; margin-left: auto; margin-right: auto;">
      <h4 style="text-align: center;">Please Kindly Login Your Account.</h4> 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4>Series</h4>
        <div class="btn-group" role="group" aria-label="Basic example">
          {% for s in series %}
            <div class="main-button">
              <a href="{% url 'app_blog:series-detail' s.pk  %}">{{ s.name }}</a>
            </div>
            &nbsp;
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>


<section class="blog-posts">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="all-blog-posts">
          <div class="row">
            {% for post in post %}
              <div class="col-lg-12">
                <div class="blog-post">
                  <div class="down-content">
                    <a href="{% url 'app_blog:post-detail' post.pk %}"><h4>{{ post.title }}</h4></a>
                    <ul class="post-info">
                      <li><a href="#"><strong>Posted By:</strong> {{ post.author }}</a></li>
                      <li><a href="#"><strong>Created On:</strong> {{ post.created_on|date:"N j Y" }}</a></li>
                      <li><a href="#"><strong>Updated On:</strong> {{ post.updated_on|timesince }} ago</a></li>
                      <br/>
                      <li>
                        <a href="#">{{ post.comment_set.all.count }} Comments</a>
                      </li>
                    </ul>
                    <p>{{ post.content }}</p>
                    <h4 style="font-weight: normal">Comments...</h4>
                    {% for comments in post.comment_set.all %}
                      {% if comments.parent_id is None %}
                      <br/>
                      <div class="comment">
                        <i class="fa fa-user"></i>
                        <b>{{ comments.commenter }}</b>
                        <div style="color:gray;">
                          {{ comments.comment_date|date:"j N Y" }} 
                          {{ comments.comment_date|time }} 
                        </div>
                        <br/>
                        {{ comments.comment_detail }}

                        <div style="text-align: right;">
                          <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comments.pk}}" aria-expanded="false" aria-controls="replyBox{{comment.pk}}">
                            Reply
                        </button>
                        <a href="{% url 'app_blog:reply-comment-create' comments.pk %}" class="btn btn-sm btn-outline-success">Reply</a>
                          &nbsp;
                          <a href="{% url 'app_blog:comment-update' comments.pk %}"><u>Edit</u></a>
                          &nbsp;
                          <a href="{% url 'app_blog:comment-delete' comments.pk %}"><u>Delete</u></a> 
                        </div>


                        <!-- Render Replies -->
                        {% include 'app_blog/comment/comment_reply.html' with replies=comments.comment_set.all %}
                    </div>

                    <div class="collapse" id="replyBox{{comments.pk}}">
                        <div class="card card-body my-2">
                            <form action="{% url 'app_blog:comment-reply' comments.pk %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="comment">Post a reply </label>
                                    <input type="text" class="form-control" name="reply_content" placeholder="Enter comment here">
                                    <input type="hidden" name="postID" value="{{post.pk}}">
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                    {% endif %}
                    {% empty %}
                        <p>No comments yet.</p>        
                  {% endfor %}

                    <br /><br />
                    <div class="button">
                      <a href="{% url 'app_blog:comment-create' post.pk %}">Add Your Comment?</a>
                    </div>

                    <div class="post-options">
                      <div class="row">
                        <div class="col-6">
                          <ul class="post-tags">
                            <li><i class="fa fa-tags"></i></li>
                            {% for tag in post.tags.all %}
                              <li><a href="#">{{ tag }}</a></li>
                            {% endfor %}
                          </ul>
                        </div>
                        <div class="col-6">
                          <ul class="post-share">
                            <li><i class="fa fa-bookmark"></i></li>
                            <li><a href="{% url 'app_blog:series-detail' post.series.pk  %}">{{ post.series }}</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}

            <div class="col-lg-12">
              <div class="main-button">
                <a href="{% url 'app_blog:post-create' %}">Add Your Own Post?</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="sidebar">
          <div class="row">
            <div class="col-lg-12">
              <div class="sidebar-item search">
                <form id="search_form" name="gs" method="GET" action="#">
                  <input
                    type="text"
                    name="q"
                    class="searchText"
                    placeholder="type to search..."
                    autocomplete="on"
                  />
                </form>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="sidebar-item recent-posts">
                <div class="sidebar-heading">
                  <h2>Recent Posts</h2>
                </div>
                <div class="content">
                  <ul>
                    {% for post in post %}
                      {% if forloop.counter <= 3 %}
                        <li>
                          <a href="{% url 'app_blog:post-detail' post.pk %}">
                            <h5>{{ post.title }}</h5>
                            <span>{{ post.author }}</span>
                          </a>
                        </li>
                      {% endif %}
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="sidebar-item categories">
                <div class="sidebar-heading">
                  <h2>Series</h2>
                </div>
                <div class="content">
                  <ul>
                    {% for s in series %}
                      <li><a href="{% url 'app_blog:series-detail' s.pk  %}">{{ s.name }}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="sidebar-item tags">
                <div class="sidebar-heading">
                  <h2>Tag</h2>
                </div>
                <div class="content">
                  <ul>
                    {% for t in tags %}
                      <li><a href="{% url 'app_blog:tag-detail' t.pk  %}">{{ t.name }}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="social-icons">
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Instagram</a></li>
          <li><a href="#">Linkedin</a></li>
        </ul>
      </div>
      <div class="col-lg-12">
        <div class="copyright-text">
          <p>
            Copyright 2023 My Blog. | Design:
            <a rel="nofollow" href="#" target="_parent">AlphaChong</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

<script language="text/Javascript">
  cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
  function clearField(t) {
    //declaring the array outside of the
    if (!cleared[t.id]) {
      // function makes it static and global
      cleared[t.id] = 1; // you could use true and false, but that's more typing
      t.value = ""; // with more chance of typos
      t.style.color = "#fff";
    }
  }
</script>

{% endblock %}

project/templates/project/master.html
<!DOCTYPE html>
<html>
<head>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/isotope.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/owl.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>


    <title>{% block title %}{% endblock %}</title>
</head>
<body>
       <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href=""><h2>My Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog-home' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_blog:post-list' %}">Blog List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_blog:series-list' %}">Series List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_blog:tag-list' %}">Tag List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app_blog:comment-list' %}">Comment List</a>
              </li>
              
              {% block content %}
              {% endblock %}


</body>
</html>